### ISSUE TITLE
点击输入框就成这样了

### ISSUE THREAD

**Issue by typhoonbb** [jwfing/FreeChat#13]
![ios simulator screen shot 2015 4 21 3 28 47](https://cloud.githubusercontent.com/assets/8253156/7247348/3e07487c-e83b-11e4-80f9-9e9e697fdaae.png)

**Comment by jwfing** [comment]
你是用最新代码吗？这个问题我已经改了的。。。

**Comment by typhoonbb** [comment]
可以QQ聊下吗  我有个问题想请教一下

**Comment by typhoonbb** [comment]
601594262
