### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by yanminhaoren** [jwfing/FreeChat#15]
![image](https://cloud.githubusercontent.com/assets/5320297/8125934/c8e9078c-111c-11e5-8bdf-22542e4daedb.png)
不知道这个问题你们是否遇到过？

**Comment by jwfing** [comment]
哦，最新代码使用了 leancloud 最新的 crashreporting framework，这是文档：
https://leancloud.cn/docs/ios_crashreporting_guide.html

会需要安装一个 leancloud crash report 的命令行工具，用来自动上传编译的符号文件，安装指令是：
`gem install --no-wrappers leancloud`

稍后我更新到 README 文档。非常感谢你的反馈！

**Comment by yanminhaoren** [comment]
3ks，问题已经解决
