### ISSUE TITLE
 failed with exit code 127

### ISSUE THREAD

**Issue by alfredlau9** [jwfing/FreeChat#16]
Users/alfred/Library/Developer/Xcode/DerivedData/FreeChat-dclizatyxtildddbwekcucxfahuy/Build/Intermediates/FreeChat.build/Debug-iphonesimulator/FreeChat.build/Script-5CCAE1481B0B0C63009276B9.sh: line 5: leancloud: command not found
Command /bin/sh failed with exit code 127

**Comment by jwfing** [comment]
谢谢反馈。
这个和 #15 是一样的，因为最新代码依赖 LeanCloud CrashReporting framework，需要先安装 leancloud 提供的符号上传工具。安装指令是

`gem install --no-wrappers leancloud`

我更新了 README 文件，你可以 rebase 一下。
