### ISSUE TITLE
iOSdemo没有请求定位权限导致ChatKit自带的发送地理位置功能不可用

### ISSUE THREAD

**Issue by ChenYilong** [jwfing/FreeChat#26]
如题，开启定位权限，参考： https://github.com/ChenYilong/iOS9AdaptationTips#2demo2_ios9新特性_更灵活的后台定位

**Comment by jwfing** [comment]
我们需要后台定位权限吗？

**Comment by ChenYilong** [comment]
发送地理位置message需要，如果没权限，地理位置获取不到，地理位置message无法发送
