### ISSUE TITLE
跟leanchat-ios比，请问freechat的目的是什么呢？ 

### ISSUE THREAD

**Issue by daheli** [jwfing/FreeChat#3]
leanchat-ios 目前也开始用v2 sdk了. 
并且可以对leanchat不足的地方进行完善或者重构。
请问freechat的目的是什么呢？

**Comment by jwfing** [comment]
LeanChat 是一个产品级的项目，功能上和微信很接近了，并不是一个很好的 LeanMessage 的学习项目；FreeChat 只是一个 Demo 级的项目，功能很简单，重在展示聊天部分的开发，会包括所有 LeanMessage 的功能。这是我对他们两个的定位。

**Comment by daheli** [comment]
做为使用leanchat的一个开发者，我希望得到了一个开箱即用的IM. 通过doc和demo，慢慢深入，完成自身app定制的需求。目前用leanchat实时通讯开发指南，我能够理解和使用一些api，但是毕竟还要从0开始code到自己的项目中。如果有一个开箱即用的IM，相信能方便和简化不少接入成本。  ：）

**Comment by jwfing** [comment]
现在 FreeChat 就是开箱即用的。
